[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'
gas_reports = ["EmergencyBrakeV2"]
solc_version = '0.8.15'
rpc_endpoints = { mainnet = "${MAINNET_RPC}" }
